---
stages:
  - validate-syntax
  - test-unit
  - acceptance-puppet4
  - acceptance-puppet5

before_script:
  - pdk --version

pdk_validate:
  stage: 'validate-syntax'
  script:
    - pdk validate
  tags:
    - puppet-tests

pdk_test_unit:
  stage: 'test-unit'
  script:
    - pdk test unit
  tags:
    - puppet-tests

acceptance_with_puppet4:
  stage: 'acceptance-puppet4'
  variables:
    BEAKER_PUPPET_COLLECTION: 'pc1'
    BEAKER_debug: 'true'
  script:
    - pdk bundle exec rake beaker:default
  tags:
    - puppet-tests
  except:
    - master

acceptance_with_puppet5:
  stage: 'acceptance-puppet5'
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_debug: 'true'
  script:
    - pdk bundle exec rake beaker:default
  tags:
    - puppet-tests
  except:
    - master
