plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - vendor/**/*
    - spec/fixtures/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/puppet/provider/**/*
    - lib/puppet/type/**/*

Metrics/AbcSize:
  Exclude:
    - lib/puppet/provider/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/puppet/provider/**/*

Metrics/MethodLength:
  Exclude:
    - lib/puppet/provider/**/*

Metrics/PerceivedComplexity:
  Exclude:
    - lib/puppet/provider/**/*

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
