.gitlab-ci.yml:
  unmanaged: true

appveyor.yml:
  delete: true

.travis.yml:
  delete: true

.rubocop.yml:
  unmanaged: true

.gitignore:
  paths:
    - '.vscode/'

Gemfile:
  required:
    ':development':
      - gem: 'beaker-rspec'
      - gem: 'beaker-puppet'
      - gem: 'beaker-docker'
      - gem: 'beaker-puppet_install_helper'
      - gem: 'beaker-module_install_helper'
      - gem: 'bolt'
      - gem: 'beaker-task_helper'
