---
HOSTS:
  ipa-server-1:
    roles:
    - default
    - master
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 2048
    ip: 192.168.44.35
  ipa-server-2:
    roles:
    - replica
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 2048
    ip: 192.168.44.36
  ipa-client-centos:
    roles:
    - client
    - centos7
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    ip: 192.168.44.37

CONFIG:
  type: foss
  loglevel: debug
