---
HOSTS:
  ipa-server-1:
    roles:
    - default
    - master
    - centos
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 2048
    ip: 192.168.44.35
  ipa-server-2:
    roles:
    - replica
    - centos
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 2048
    ip: 192.168.44.36
  ipa-client-centos:
    roles:
    - client
    - client-centos7
    - centos
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 1024
    ip: 192.168.44.37
  ipa-client-ubuntu16:
    roles:
    - client
    - client-ubuntu16
    platform: ubuntu-1604-amd64
    hypervisor: vagrant
    box: geerlingguy/ubuntu1604
    vagrant_memsize: 1024
    ip: 192.168.44.38

CONFIG:
  type: foss
  loglevel: debug
