---
HOSTS:
  ipa-server-1:
    roles:
    - default
    - master
    - centos
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 2048
    vagrant_cpus: 2
  ipa-server-2:
    roles:
    - replica
    - centos
    platform: el-7-x86_64
    hypervisor: vagrant
    box: centos/7
    box_version: 1809.01
    box_check_update: false
    vagrant_memsize: 2048
    vagrant_cpus: 2
  ipa-client-ubuntu18:
    roles:
    - client
    platform: ubuntu-1804-amd64
    hypervisor: vagrant
    box: ubuntu/bionic64
    box_version: 20191114.0.0
    box_check_update: false
    vagrant_memsize: 1024

CONFIG:
  type: foss
  loglevel: debug
