---
HOSTS:
  ipa-server-1:
    roles:
    - default
    - master
    platform: el-7-x86_64
    hypervisor: vagrant
    box: geerlingguy/centos7
    vagrant_memsize: 2048
    ip: 192.168.44.35
    forwarded_ports:
      httpd1:
        from: 8000
        to: 8000
      httpd2:
        from: 8440
        to: 8440
CONFIG:
  type: foss
  loglevel: debug
